FROM debian:11.9

# Install packages
#
# The list was obtained from:
#  - https://github.com/ecmwf-actions/runners-infra/blob/main/project/install_build_deps.yml
#

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
      && apt-get install -y --no-install-recommends \
            software-properties-common \
            vim wget curl \
            build-essential \
            git \
            gfortran \
            cmake \
            ninja-build \
            gdb \
            bison flex \
            libssl-dev libaec-dev libpng-dev libeigen3-dev liblapack-dev libncurses5-dev libnetcdf-dev \
            libnetcdff-dev libblas-dev libpq-dev libfftw3-dev \
            python3 python3-dev python3-pip \
            perl \
            qtbase5-dev libqt5svg5-dev libqt5xmlpatterns5-dev \
            libboost-dev libboost-system-dev libboost-timer-dev libboost-chrono-dev libboost-filesystem-dev \
            libboost-program-options-dev libboost-python-dev libboost-date-time-dev libboost-test-dev \
            proj-bin libproj-dev \
            libexpat1-dev libgdbm-dev libtirpc-dev \
            unzip libopenjp2-7-dev \
            tini \
      && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /

ENTRYPOINT ["/usr/bin/tini", "--", "/entrypoint.sh"]
CMD ["/home/runner/run.sh"]
