FROM ubuntu:24.04

# Install packages
#
# The list was obtained from:
#  - https://github.com/ecmwf-actions/runners-infra/blob/main/project/install_build_deps.yml
#

ENV DEBIAN_FRONTEND noninteractive

# Install development packages

RUN apt-get update -y \
      && apt-get install -y --no-install-recommends \
            software-properties-common \
            vim wget curl \
            build-essential \
            git \
            gcc g++ gfortran \
            gcc-9 g++9 gfortran-9 \
            gcc-10 g++10 gfortran-10 \
            gcc-11 g++-11 gfortran-11 \
            gcc-12 g++-12 gfortran-12 \
            gcc-13 g++-13 gfortran-13 \
            gcc-14 g++-14 gfortran-14 \
            clang \
            clang-14 \
            clang-15 \
            clang-16 \
            clang-17 \
            clang-18 \
            ninja-build \
            gdb \
            bison flex \
            libssl-dev \
            python3 python3-dev python3-pip \
            qtbase5-dev libqt5svg5-dev libqt5xmlpatterns5-dev \
            libboost-dev libboost-system-dev libboost-timer-dev libboost-chrono-dev libboost-filesystem-dev \
            libboost-program-options-dev libboost-python-dev libboost-date-time-dev libboost-test-dev \
            unzip \
            tini \
      && rm -rf /var/lib/apt/lists/*

# Install latest CMake, at this time 

# Use CMAKE_ARCH=x86_64 for amd64 and CMAKE_ARCH=aarch64 for arm64!
ARG CMAKE_ARCH=aarch64 
ARG CMAKE_VERSION=3.30.4

RUN cd /opt \
        && wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-${CMAKE_ARCH}.tar.gz \
        && tar zxf cmake-${CMAKE_VERSION}-linux-${CMAKE_ARCH}.tar.gz \
        && ln -s cmake-${CMAKE_VERSION}-linux-${CMAKE_ARCH} cmake \
        && rm cmake-${CMAKE_VERSION}-linux-${CMAKE_ARCH}.tar.gz
ENV PATH="/opt/cmake/bin:${PATH}"

COPY entrypoint.sh /

ENTRYPOINT ["/usr/bin/tini", "--", "/entrypoint.sh"]
CMD ["/home/runner/run.sh"]